# How to run:

version: '2'
services:
  pf-db:
     container_name: pf-db
     image: 'bitnami/mongodb:latest'
     ports:
       - "27018:27017"
     volumes:
       - vol/pfDB/:/bitnami

  pf-api:
    container_name: pf-api
    build:
      context: .
      dockerfile: Dockerfile_api
    image: pf-api:latest
    depends_on:
      - "pf-db"
    expose:
      - "3009"
    ports:
      - "4601:3009"
    environment:
      - NODE_ENV=production
    command: ["./wait-for-it.sh", "-t", "0", "paisagem-db:3306", "--", "npm","start", ]
